Repository 2011-libra/notables, pull requests merged in 2021-02, with the labels that each got.

#15 Text editor
  app/components/index.js
  app/components/texteditor/Texteditor.css
  app/components/texteditor/texteditor.js
  app/components/texteditor/toolbar.js
  app/main.js
  package-lock.json
  package.json
  public/index.css
  public/index.html
Labels: enhancement

#19 T1-FE Export: Created component to download rich text file
  app/components/texteditor/Texteditor.css
  app/components/texteditor/codeeditor.js
  app/components/texteditor/texteditor.js
Labels: enhancement

#21 FE: navbar with errors
  app/components/navbar/dropdownmenu.js
  app/components/navbar/navbar.css
  app/components/navbar/navbar.js
  app/components/navbar/navitem.js
  app/main.js
  package-lock.json
  package.json
Labels: enhancement

#26 T1-FE Export: Added Turndown library, converting HTML to MD via download
  app/components/texteditor/texteditor.js
  app/components/texteditor/toolbar.js
  public/index.html
Labels: enhancement

#32 T1-FE: Added Temp Logo/Name, Icons & adjusted dropdown
  app/components/navbar/dropdownmenu.js
  app/components/navbar/nav.css
  app/components/navbar/nav.js
  app/components/navbar/navbar.css
  app/components/navbar/navbar.js
  app/components/navbar/navitem.js
  app/main.js
  package-lock.json
  package.json
  public/images/logo.png
Labels: enhancement

#33 T1-FE: Edited texteditor.js and dropzone.js
  app/components/import/dropzone.js
  app/components/texteditor/texteditor.js
  app/main.js
Labels: edit

#36 T1-FE: Feature added: imported files now displayed in editor
  app/components/texteditor/texteditor.js
Labels: enhancement

#41 T1-FE: Added styles and export functionality to nav
  app/components/navbar/nav.css
  app/components/navbar/nav.js
  app/components/texteditor/texteditor.js
  package-lock.json
Labels: enhancement

#45 Testing import
  app/components/texteditor/texteditor.js
  public/index.html
Labels: enhancement

#50 T1-FE: Fixed error in toolbar dropdown that dealt with the normal option
  app/components/texteditor/texteditor.js
  app/components/texteditor/toolbar.js
Labels: edit

#55 Feat/navbar
  app/components/import/dropzone.js
  app/components/navbar/dropdownmenu.js
  app/components/navbar/nav.js
  app/components/navbar/navbar.css
  app/components/navbar/navbar.js
  app/components/navbar/navitem.js
  app/components/texteditor/texteditor.js
  app/main.js
  app/redux/import.js
  app/redux/index.js
  public/index.html
  server/docker/81992021191515966/code.tar
Labels: enhancement

#56 Testing login
  app/components/login/login.css
  app/components/login/login.js
  app/components/navbar/nav.css
  app/components/navbar/nav.js
  app/components/texteditor/Texteditor.css
  app/components/texteditor/texteditor.js
  app/main.js
  app/redux/index.js
  app/redux/user.js
  app/routes.js
  package-lock.json
  package.json
  server/api/user.js
  server/docker/81992021191515966/code.tar
Labels: edit, enhancement

#58 T2-FE: Changed logo and name color to white
  app/components/navbar/nav.css
Labels: edit

#80 T2-FE: Created modal popup for users to learn more
  app/components/about/about.js
  app/components/navbar/nav.js
  app/components/texteditor/Texteditor.css
Labels: enhancement

#84 T2-FE: Edited/Styled drawer/dropzone component
  app/components/import/Dropzone.css
  app/components/import/dropzone.js
  app/components/navbar/nav.css
  app/components/navbar/nav.js
Labels: enhancement

#89 T2-FE: Fixed alignment of navbar icons
  app/components/navbar/nav.css
  app/components/navbar/nav.js
Labels: enhancement

#90 Testing modal
  app/components/about/about.js
  app/components/import/dropzone.js
  app/components/navbar/nav.js
  app/components/texteditor/toolbar.js
  public/index.css
Labels: edit

#93 Feat/navbar
  app/components/import/dropzone.js
  public/index.html
Labels: enhancement

#102 TE2-FE: Added new rules to hyperlink & renamed export to download
  app/components/navbar/nav.js
  app/components/texteditor/toolbar.js
Labels: edit, enhancement

#103 Feat/navbar
  app/components/navbar/nav.css
  app/components/navbar/nav.js
  app/components/texteditor/Texteditor.css
  app/utils/auto-save.js
  package-lock.json
  package.json
  public/index.html
Labels: enhancement

#105 T2-FE: Edited About us statement & deleted inline styles
  app/components/about/about.js
  app/components/texteditor/texteditor.js
  app/utils/auto-save.js
  public/index.css
Labels: edit

#114 T2-FE: Delete button gives pop up instead of alert
  app/components/texteditor/toolbar.js
  app/utils/clearDoc.js
Labels: edit, enhancement

#113 T2-FE: User cannot download if text editor is empty
  app/components/navbar/nav.js
Labels: enhancement

#115 T2-FE: Changed alert boxes to modal pop ups
  app/components/texteditor/toolbar.js
  app/utils/addCodeBlock.js
  app/utils/auto-save.js
  app/utils/createCodeAlert.js
  app/utils/hyperlink.js
  app/utils/hyperlinkAlert.js
Labels: enhancement
